language: java

before_install: "git clone -b maven `git config --get remote.origin.url` target/maven"
script: "mvn deploy --settings target/maven/settings.xml"

after_success:
  - mvn clean test jacoco:report coveralls:report

branches:
  except:
    - maven
